### ISSUE TITLE
Getting issue with reuse

### ISSUE THREAD

**Issue by tremblerz** [uclaacmai/Generative-Adversarial-Network-Tutorial#8]
It seems that `reuse` should be made True when getting sample image from generator. Also, for getting every new image I have to run the main training again. When I am trying to use the notebook as it is, I get the following error.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-49-973589bcdbd1> in <module>()
----> 1 sample_image = generator(z_placeholder, 1, z_dimensions)
      2 z_batch = np.random.normal(-1, 1, size=[1, z_dimensions])
      3 temp = (sess.run(sample_image, feed_dict={z_placeholder: z_batch}))
      4 my_i = temp.squeeze()
      5 plt.imshow(my_i)#, cmap='gray_r')

<ipython-input-6-4f1901fc9859> in generator(z, batch_size, z_dim, reuse)
     16         output1_shape = [batch_size, s8, s8, g_dim*4]
     17         W_conv1 = tf.get_variable('g_wconv1', [5, 5, output1_shape[-1], int(h0.get_shape()[-1])], 
---> 18                                   initializer=tf.truncated_normal_initializer(stddev=0.1))
     19         b_conv1 = tf.get_variable('g_bconv1', [output1_shape[-1]], initializer=tf.constant_initializer(.1))
     20         H_conv1 = tf.nn.conv2d_transpose(h0, W_conv1, output_shape=output1_shape, 

~/Learning/Python/ai-notebook/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py in get_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
   1201       partitioner=partitioner, validate_shape=validate_shape,
   1202       use_resource=use_resource, custom_getter=custom_getter,
-> 1203       constraint=constraint)
   1204 get_variable_or_local_docstring = (
   1205     """%s

~/Learning/Python/ai-notebook/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py in get_variable(self, var_store, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
   1090           partitioner=partitioner, validate_shape=validate_shape,
   1091           use_resource=use_resource, custom_getter=custom_getter,
-> 1092           constraint=constraint)
   1093 
   1094   def _get_partitioned_variable(self,

~/Learning/Python/ai-notebook/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py in get_variable(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint)
    423           caching_device=caching_device, partitioner=partitioner,
    424           validate_shape=validate_shape, use_resource=use_resource,
--> 425           constraint=constraint)
    426 
    427   def _get_partitioned_variable(

~/Learning/Python/ai-notebook/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py in _true_getter(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, constraint)
    392           trainable=trainable, collections=collections,
    393           caching_device=caching_device, validate_shape=validate_shape,
--> 394           use_resource=use_resource, constraint=constraint)
    395 
    396     if custom_getter is not None:

~/Learning/Python/ai-notebook/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource, constraint)
    740                          "reuse=tf.AUTO_REUSE in VarScope? "
    741                          "Originally defined at:\n\n%s" % (
--> 742                              name, "".join(traceback.format_list(tb))))
    743       found_var = self._vars[name]
    744       if not shape.is_compatible_with(found_var.get_shape()):

ValueError: Variable generator/g_wconv1 already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "<ipython-input-6-4f1901fc9859>", line 18, in generator
    initializer=tf.truncated_normal_initializer(stddev=0.1))
  File "<ipython-input-14-9c8e42d9057a>", line 2, in <module>
    Gz = generator(z_placeholder, batch_size, z_dimensions) #Gz holds the generated images
  File "/Users/tremblerz/Learning/Python/ai-notebook/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
```

**Comment by duongkstn** [comment]
I have same error :(

**Comment by wsteven24** [comment]
I solved the issue by commenting the "if (reuse):"

**Comment by arvindr9** [comment]
Did you comment out "if (reuse)" from the generator or from the discriminator? I'm still continuing to get the same error.

**Comment by wsteven24** [comment]
from the generator. Just like this:
def generator(z, batch_size, z_dim, reuse=False):
    with tf.variable_scope('generator') as scope:
        #if (reuse):
        tf.get_variable_scope().reuse_variables()
        g_dim = 64 #Number of filters of first layer of generator 
        ...

**Comment by lanejere5** [comment]
Commenting out `if(reuse)` is the wrong solution (since it's needed earlier in the worksheet). Instead, when calling the generator to make an image, pass a value of `True` for reuse:

`sample_image = generator(z_placeholder, 1, z_dimensions,True)`

**Comment by wsteven24** [comment]
Excellent! @lane203j your solution worked for me. Thanks.

**Comment by don-tpanic** [comment]
I tried sample_image = generator(z_placeholder, 1, z_dimensions,True) but it still gives me:
assert tf.get_variable_scope().reuse == False, "Houston tengo un problem"
AssertionError: Houston tengo un problem

Thanks in advance

**Comment by funwey** [comment]
hi
The new tutorial code has all the sample_image lines commented out, but I still have the "Houston tengo un problem" but this occurs at line 290.  Appreciate any help.

**Comment by shikharras** [comment]
Hey, why is it that we need to train again to generate a new image? Is this because of a 'mode collapse' in this architecture?

**Comment by KonstantineMushegian-TRI** [comment]
When getting the sample image in the last section, set re-use in the generator to true. No errors occur. You do want it to re-use the variables that resulted after the training.

**Comment by rohan-varma** [comment]
This should be fixed now. Thanks everyone!
